CREATE TABLE "tb_model_total_sales_order" (
	"iindex"	INTEGER NOT NULL DEFAULT 1 PRIMARY KEY AUTOINCREMENT UNIQUE,
	"strdate"	TEXT NOT NULL,
	"strdocumenttype"	TEXT NOT NULL,
	"strdocumentcode"	TEXT NOT NULL,
	"strdocumentstatus"	TEXT NOT NULL,
	"strcustomer"	TEXT NOT NULL,
	"strsalesdepartment"	TEXT NOT NULL,
	"strsalesmen"	TEXT NOT NULL,
	"strclosedstatus"	TEXT NOT NULL,
	"strmaterielcode"	TEXT NOT NULL,
	"strmaterielname"	TEXT NOT NULL,
	"strspecifications"	TEXT NOT NULL,
	"strsalesunit"	TEXT NOT NULL,
	"isalesnums"	INTEGER,
	"runitprice"	REAL,
	"runitpriceincludtax"	REAL,
	"rtotalpriceincludtax"	REAL,
	"strrequiredate"	TEXT,
	"rcumulativedelivery"	REAL,
	"rcumulativereturn"	REAL,
	"rtotalprice_rmb"	REAL,
	"rtotalpriceincludtax_rmb"	REAL,
	"irestquantity"	INTEGER,
	"strbusinessstatus"	TEXT,
	"strcyclespare"	TEXT,
	"strproductioncode"	TEXT
)